### ISSUE TITLE
 print green("Updating Required Files") ERROR

### ISSUE THREAD

**Issue by x7peeps** [PentestBox/scripts#1]
when i type **sqlmap** it told me i should update the new sqlmap.  so i **update** the tools.but i got this py error.PLS hellp:)
> update
  File "D:\HackProgram\PentestBox\bin\scripts\update.py", line 14
    print green("Updating Required Files")
              ^
SyntaxError: invalid syntax

**Comment by x7peeps** [comment]
All is ok,After i changed the sys path to **%yoursyspath%PentestBox\base\python\Scripts** which is py2.7...

**Comment by exploitprotocol** [comment]
I guess you have local installation of Python 3.x . I fixed that before by removin %PATH% from the Pentestbox path variable. https://github.com/PentestBox/configV2/commit/8bd3024c05ec17141f1bf5d6a6660b6460587398

Since you are using PentestBox from D:\HackProgram\PentestBox instead of C:\PentestBox which is recommended on official website, that is possible the reason for this issue. 

I have seen that issue only in people using windows 7, i will look in to it to fix in those systems as well. 

Thanks for reporting it 😃

**Comment by x7peeps** [comment]
before i install the Pentest Box ,i had my python3.5 and it's sys path in my PC, so when i saw SyntaxError: invalid syntax, and googled it , it seems like some words dont support in py3.5, so i changed py path. PentestBox\base\python;PentestBox\base\python\script;  then all gones alright;)

**Comment by exploitprotocol** [comment]
Cool, glad to know that you fixed the problem :)
